name: Flutter CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build and test
      run: |
        flutter build apk